# AUTO BUILDS #
# From https://github.com/Poeschl/Hassio-Addons
# name: slug/filename ; could be slug/config.* for all files
adsb-multi-portal-feeder: adsb-multi-portal-feeder/config.* # Image : yes
angryipscanner: angry-ip-scanner/config.* # Image : yes
